import { ApplicationState } from '../types/types';

const state: ApplicationState = {
  theme: 'dark',
  startDay: new Date(),
  events: {
    '2021-02-01': [
      {
        id: 'dasdafdfdsf',
        title: 'Party',
        description: 'Cancun',
        color: 'yellow',
        date: '2021-02-01',
        time: '07:39',
      },
    ],
    '2021-02-12': [
      {
        id: 'Sx4i12NoOd',
        title: 'Get groceries',
        description: 'New York',
        color: 'salmon',
        date: '2021-02-12',
        time: '02:25',
      },
      {
        id: 'dD7e9cIeNE',
        title: 'Movies',
        description: 'Chicago',
        color: 'cyan',
        date: '2021-02-12',
        time: '06:25',
      },
    ],
    '2021-02-15': [
      {
        id: 'To_Q9dcjka',
        title: 'Play Soccer',
        description: 'Paris',
        color: 'pink',
        date: '2021-02-15',
        time: '02:25',
      },
    ],
    '2021-02-25': [
      {
        id: 'rcpaO-ySIR',
        title: 'Dentist',
        description: 'Dubai',
        color: 'pink',
        date: '2021-02-25',
        time: '02:25',
      },
    ],
    '2021-02-02': [
      {
        id: 'Vsr1sr9sFs',
        title: 'Relax',
        description: 'Tokyo',
        color: 'green',
        date: '2021-02-02',
        time: '02:25',
      },
    ],
    '2021-02-19': [
      {
        id: 'DW6dkNU',
        title: 'Play Soccer',
        description: 'San Francisco',
        color: 'yellow',
        date: '2021-02-19',
        time: '02:25',
      },
    ],
    '2021-02-28': [
      {
        id: 'OJVL0Uhuoe',
        title: 'Study',
        description: 'São Paulo',
        color: 'salmon',
        date: '2021-02-28',
        time: '02:25',
      },
    ],
    '2021-02-29': [
      {
        id: 'jsndfjkdsnfds',
        title: 'Safari',
        description: 'New York',
        color: 'cyan',
        date: '2021-02-29',
        time: '02:38',
      },
    ],
    '2021-02-07': [
      {
        id: '7DjuG6wqKp',
        title: 'Boat Party',
        description: 'New York',
        color: 'cyan',
        date: '2021-02-07',
        time: '02:38',
      },
      {
        id: '3OkpTQhYga',
        title: 'Study',
        description: 'London',
        color: 'salmon',
        date: '2021-02-07',
        time: '02:37',
      },
      {
        id: 'bzQg0d5jvF',
        title: 'Relax',
        description: 'São Paulo',
        color: 'pink',
        date: '2021-02-07',
        time: '02:38',
      },
    ],
    '2021-02-31': [
      {
        id: '_F0MHfpPzu',
        title: 'Work',
        description: 'Limerick',
        color: 'yellow',
        date: '2021-02-31',
        time: '07:39',
      },
    ],
    '2021-02-09': [
      {
        id: 'dasdafdfdsf',
        title: 'Party',
        description: 'Cancun',
        color: 'yellow',
        date: '2021-02-09',
        time: '07:39',
      },
    ],
    '2021-03-12': [
      {
        id: 'Sx4i12NoOd',
        title: 'Get groceries',
        description: 'New York',
        color: 'salmon',
        date: '2021-03-12',
        time: '02:25',
      },
      {
        id: 'dD7e9cIeNE',
        title: 'Movies',
        description: 'Chicago',
        color: 'cyan',
        date: '2021-03-12',
        time: '06:25',
      },
    ],
    '2021-03-15': [
      {
        id: 'To_Q9dcjka',
        title: 'Play Soccer',
        description: 'Paris',
        color: 'pink',
        date: '2021-03-15',
        time: '02:25',
      },
    ],
    '2021-03-25': [
      {
        id: 'rcpaO-ySIR',
        title: 'Dentist',
        description: 'Dubai',
        color: 'pink',
        date: '2021-03-25',
        time: '02:25',
      },
    ],
    '2021-03-02': [
      {
        id: 'Vsr1sr9sFs',
        title: 'Relax',
        description: 'Tokyo',
        color: 'green',
        date: '2021-03-02',
        time: '02:25',
      },
    ],
    '2021-03-19': [
      {
        id: 'DW6dkNU',
        title: 'Play Soccer',
        description: 'San Francisco',
        color: 'yellow',
        date: '2021-03-19',
        time: '02:25',
      },
    ],
    '2021-03-28': [
      {
        id: 'OJVL0Uhuoe',
        title: 'Study',
        description: 'São Paulo',
        color: 'salmon',
        date: '2021-03-28',
        time: '02:25',
      },
    ],
    '2021-03-29': [
      {
        id: 'jsndfjkdsnfds',
        title: 'Safari',
        description: 'New York',
        color: 'cyan',
        date: '2021-03-29',
        time: '02:38',
      },
    ],
    '2021-03-31': [
      {
        id: '7DjuG6wqKp',
        title: 'Boat Party',
        description: 'New York',
        color: 'cyan',
        date: '2021-03-31',
        time: '02:38',
      },
      {
        id: '3OkpTQhYga',
        title: 'Study',
        description: 'London',
        color: 'salmon',
        date: '2021-03-31',
        time: '03:37',
      },
      {
        id: '7DjuG6wqKp',
        title: 'Boat Party',
        description: 'New York',
        color: 'cyan',
        date: '2021-03-31',
        time: '02:38',
      },
    ],
    '2021-03-30': [
      {
        id: '_F0MHfpPzu',
        title: 'Work',
        description: 'Limerick',
        color: 'yellow',
        date: '2021-03-30',
        time: '07:39',
      },
    ],
    '2021-04-01': [
      {
        id: 'dasdafdfdsf',
        title: 'Party',
        description: 'Cancun',
        color: 'yellow',
        date: '2021-04-01',
        time: '07:39',
      },
    ],
    '2021-04-12': [
      {
        id: 'Sx4i12NoOd',
        title: 'Get groceries',
        description: 'New York',
        color: 'salmon',
        date: '2021-04-12',
        time: '02:25',
      },
      {
        id: 'dD7e9cIeNE',
        title: 'Movies',
        description: 'Chicago',
        color: 'cyan',
        date: '2021-04-12',
        time: '06:25',
      },
    ],
    '2021-04-15': [
      {
        id: 'To_Q9dcjka',
        title: 'Play Soccer',
        description: 'Paris',
        color: 'pink',
        date: '2021-04-15',
        time: '02:25',
      },
    ],
    '2021-04-25': [
      {
        id: 'rcpaO-ySIR',
        title: 'Dentist',
        description: 'Dubai',
        color: 'pink',
        date: '2021-04-25',
        time: '02:25',
      },
    ],
    '2021-04-02': [
      {
        id: 'Vsr1sr9sFs',
        title: 'Relax',
        description: 'Tokyo',
        color: 'green',
        date: '2021-04-02',
        time: '02:25',
      },
      {
        id: 'bzQg0d5jvF',
        title: 'Relax',
        description: 'São Paulo',
        color: 'pink',
        date: '2021-04-02',
        time: '02:38',
      },
    ],
    '2021-04-19': [
      {
        id: 'DW6dkNU',
        title: 'Play Soccer',
        description: 'San Francisco',
        color: 'yellow',
        date: '2021-04-19',
        time: '02:25',
      },
    ],
    '2021-04-28': [
      {
        id: 'OJVL0Uhuoe',
        title: 'Study',
        description: 'São Paulo',
        color: 'salmon',
        date: '2021-04-28',
        time: '02:25',
      },
    ],
    '2021-04-29': [
      {
        id: 'jsndfjkdsnfds',
        title: 'Safari',
        description: 'New York',
        color: 'cyan',
        date: '2021-04-29',
        time: '02:38',
      },
    ],
    '2021-04-07': [
      {
        id: '7DjuG6wqKp',
        title: 'Boat Party',
        description: 'New York',
        color: 'cyan',
        date: '2021-04-07',
        time: '02:38',
      },
      {
        id: '3OkpTQhYga',
        title: 'Study',
        description: 'London',
        color: 'salmon',
        date: '2021-04-07',
        time: '04:37',
      },
      {
        id: 'bzQg0d5jvF',
        title: 'Relax',
        description: 'São Paulo',
        color: 'pink',
        date: '2021-04-07',
        time: '04:38',
      },
    ],
    '2021-04-31': [
      {
        id: '_F0MHfpPzu',
        title: 'Work',
        description: 'Limerick',
        color: 'yellow',
        date: '2021-04-31',
        time: '07:39',
      },
    ],
    '2021-04-09': [
      {
        id: 'dasdafdfdsf',
        title: 'Party',
        description: 'Cancun',
        color: 'yellow',
        date: '2021-04-09',
        time: '07:39',
      },
    ],
  },
  showCreateEvent: false,
  showDayDetail: false,
  dayInDetail: new Date(),
  showEditEvent: false,
  eventToEdit: {
    id: '',
    title: '',
    description: '',
    color: 'cyan',
    date: '',
    time: '00:00',
  },
};

export default state;